### ISSUE TITLE
Move common stencils from pyFV3 to NDSL

### ISSUE THREAD

**Issue by oelbert** [NOAA-GFDL/NDSL#18]
Basic stencil operations like copy, set values, multiply, divide, sign, and dim currently live in pyFV3/stencils/basic_operations.py, but ndsl/stencils is a more natural place for these utility stencils. This also simplifies the dependencies of the model components significantly.

**Comment by fmalatino** [comment]
Will be fixed in [21](https://github.com/NOAA-GFDL/NDSL/pull/21) and [12](https://github.com/NOAA-GFDL/PyFV3/pull/12)
